---
- name: Install the mysql remote repo
  yum: name=http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm state=present

- name: Install the mysql rpm from a remote repo
  yum: name=mysql-community-server state=present
  register: mysql_installed

- name: Download mysql-java-connector
  shell: 'wget http://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-{{ mysql_connector_version }}.tar.gz
      -O /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz creates=/tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz'
  register: mysqlconnector_downloaded

- name: Extract mysql-java-connector
  shell: 'tar xzf /tmp/mysql-connector-java-{{ mysql_connector_version }}.tar.gz -C /tmp'
  register: mysqlconnector_extracted
  when: mysqlconnector_downloaded|changed

- name: Install mysql-java-connector
  shell: 'mv /tmp/mysql-connector-java-{{ mysql_connector_version }}/mysql-connector-java-{{ mysql_connector_version }}-bin.jar /opt/alfresco/tomcat/lib/ && chown alfresco:alfresco /opt/alfresco/tomcat/lib/mysql-connector-java-{{ mysql_connector_version }}-bin.jar'
  when: mysqlconnector_extracted|changed

- name: Cleanup mysql-java-connector
  shell: 'rm -rf /tmp/mysql-connector-java-{{ mysql_connector_version }}'
  when: mysqlconnector_extracted|changed

- name: Configure transaction isolation
  lineinfile: dest=/etc/my.cnf insertafter="sql-mode" line="transaction-isolation=READ-COMMITTED"

- name: Start and enable the mysql service
  service: name=mysqld state=restarted enabled=yes
  when: mysql_installed|changed

- name: Wait for the service up
  wait_for: port=3306 delay=30
  when: mysql_installed|changed

- name: Update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - 127.0.0.1
   - ::1
   - localhost
  when: mysql_installed|changed

- name: Create alfresco database
  mysql_db: login_user=root login_password={{ mysql_root_db_pass }} login_host={{ alfresco_db_host }} name={{ alfresco_db_name }} state=present

- name: Create alfresco_user / roles
  mysql_user: login_user=root login_password={{ mysql_root_db_pass }} login_host={{ alfresco_db_host }} name={{ alfresco_db_user }} password={{ alfresco_db_password}} priv={{ alfresco_db_name }}.*:ALL state=present
