---
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  
- include: setup-Ubuntu.yml
  when: ansible_os_family == 'Debian'
  
# Install tomcat
- include: tomcat.yml

# Install tomcat
- include: mysql-java-connector.yml
  when: setup_mysql_java_connector

# Install Alfresco
- include: alfresco.yml

# Install Alfresco Solr
- include: solr.yml
  when: setup_solr