---
# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

# Install tomcat
- include: tomcat.yml

# Install Alfresco
- include: alfresco.yml

# Install Alfresco Solr
- include: solr.yml
  when: setup_solr