---
- name: Create group
  group: name={{ alfresco_group }} state=present

- name: Create user
  user: name={{ alfresco_user }} home={{ alfresco_user_home }} uid={{ alfresco_uid }} shell=/bin/sh group={{ alfresco_group }} state=present

- name: Create folder
  file: path={{ alfresco_user_home }} state=directory owner={{ alfresco_user }} group={{ alfresco_group }} mode=0770
  
- name: Download tomcat
  shell: 'wget http://archive.apache.org/dist/tomcat/tomcat-{{ tomcat_version|first() }}/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz
    -O /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz creates=/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz'
  register: tomcat_downloaded

- name: Extract tomcat
  shell: 'tar xzf /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz -C /opt/'
  register: tomcat_extracted
  when: tomcat_downloaded|changed

- name: Create tomcat symlink
  file: path={{ alfresco_user_home }}/tomcat state=link src=/opt/apache-tomcat-{{ tomcat_version }}
  when: tomcat_extracted|changed

- name: Set shared loader
  lineinfile: dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/catalina.properties regexp="^shared.loader=" line="shared.loader=${catalina.base}/shared/classes,${catalina.base}/shared/lib/*.jar"

- name: set port {{ tomcat_port }} to tomcat
  template:
    src=server.xml.j2
    dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/server.xml
    owner={{alfresco_user}}
    group={{alfresco_group}}
    mode=0755

- name: Set SSLAuthenticator
  lineinfile: dest=/opt/apache-tomcat-{{ tomcat_version }}/conf/context.xml insertbefore="^</Context>" line="    <Valve className=\"org.apache.catalina.authenticator.SSLAuthenticator\" securePagesWithPragma=\"false\" />"
