---
- name: Set shared loader
  lineinfile: dest=opt/alfresco/tomcat/conf/catalina.properties regexp="^shared.loader=" line="shared.loader=${catalina.base}/shared/classes,${catalina.base}/shared/lib/*.jar"

- name: Set SSLAuthenticator
  lineinfile: dest=opt/alfresco/tomcat/conf/context.xml insertbefore="^</Context>" line="    <Valve className=\"org.apache.catalina.authenticator.SSLAuthenticator\" securePagesWithPragma=\"false\" />"
