---
- hosts: all
  sudo: True
  roles:
      - common
      - { role: openjdk, when: "java_type == 'open'"}
      - { role: java, when: "java_type == 'sun'"}
      - { role: tomcat, tags: ['app'] }
      - { role: mysql, when: "alfresco_db == 'mysql'", tags: ['db'] }
      - {role: postgresql, when: "alfresco_db == 'postgresql'"}
      - tools
      - { role: alfresco, tags: ['app'] }
      - { role: solr, when: "alfresco_indexing == 'solr'" }
