---
- name: Download alfresco community
  shell: 'wget http://dl.alfresco.com/release/community/{{ alfresco_version }}-build-{{ alfresco_build }}/alfresco-community-{{ alfresco_version }}.zip
    -O /tmp/alfresco-community-{{ alfresco_version }}.zip creates=/tmp/alfresco-community-{{ alfresco_version }}.zip'
  register: alfresco_downloaded

- name: Extract alfresco
  command: unzip -o /tmp/alfresco-community-{{ alfresco_version }}.zip -d /tmp/alfresco/
  register: alfresco_extracted
  when: alfresco_downloaded|changed

- name: Install alfresco to tomcat
  shell: cp -rf /tmp/alfresco/web-server/* {{ alfresco_user_home }}/tomcat/
  when: alfresco_extracted|changed

- name: Install alfresco bin, licenses and readme
  shell: cp -rf /tmp/alfresco/bin /tmp/alfresco/licenses /tmp/alfresco/README.txt {{ alfresco_user_home }}/tomcat/
  when: alfresco_extracted|changed

- name: Cleanup alfresco unzipped
  file: path=/tmp/alfresco state=absent
  when: alfresco_extracted|changed

- name: Create alfresco alf_data directory
  file: path={{ alfresco_user_home }}/alf_data state=directory owner={{ alfresco_user }} group=alfresco
  when: alfresco_extracted|changed

- name: Install libreoffice startup script
  copy: src=start_oo.sh dest={{ alfresco_user_home }}/start_oo.sh owner=alfresco group=alfresco mode=0744
  when: alfresco_extracted|changed

- name: Install alfresco startup script
  template: src=alfresco.sh dest={{ alfresco_user_home }}/alfresco.sh owner=alfresco group=alfresco mode=0744
  when: alfresco_extracted|changed

- name: Install alfresco init script
  template: src=alfresco dest=/etc/init.d/alfresco owner=root group=root mode=0755
  when: alfresco_extracted|changed

- name: Install alfresco global configuration
  template: src=alfresco-global.properties dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco-global.properties owner=alfresco group=alfresco mode=0644
  when: alfresco_extracted|changed

- name: Set alfresco file permissions
  file: path={{ alfresco_user_home }} owner={{ alfresco_user }} group=alfresco recurse=yes
  when: tomcat_downloaded|changed

- name: Start alfresco server
  service: name=alfresco state=started
  when: alfresco_extracted|changed

- name: Relax security constraint for solr http comunication
  template: src=web.xml dest={{ alfresco_user_home }}/tomcat/webapps/alfresco/WEB-INF/web.xml owner=alfresco group=alfresco mode=0644
  when: alfresco_extracted|changed

- name: Restart alfresco server
  service: name=alfresco state=restarted
  when: alfresco_extracted|changed 
