---
- name: Download alfresco community
  shell: 'wget http://dl.alfresco.com/release/community/{{ alfresco_version }}-build-{{ alfresco_build }}/alfresco-community-{{ alfresco_version }}.zip
    -O /tmp/alfresco-community-{{ alfresco_version }}.zip creates=/tmp/alfresco-community-{{ alfresco_version }}.zip'
  register: alfresco_downloaded

- name: Extract alfresco
  command: unzip -o /tmp/alfresco-community-{{ alfresco_version }}.zip -d /tmp/alfresco/
  register: alfresco_extracted
  when: alfresco_downloaded|changed

- name: Install alfresco to tomcat
  shell: cp -rf /tmp/alfresco/web-server/* {{ alfresco_user_home }}/tomcat/
  when: alfresco_extracted|changed

- name: Install alfresco bin, licenses and readme
  shell: cp -rf /tmp/alfresco/bin /tmp/alfresco/licenses /tmp/alfresco/README.txt {{ alfresco_user_home }}/
  when: alfresco_extracted|changed

- name: Cleanup alfresco unzipped
  file: path=/tmp/alfresco state=absent
  when: alfresco_extracted|changed

- name: Create alfresco alf_data directory
  file: path={{ alfresco_user_home }}/alf_data state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted|changed

- name: Create alfresco amp directory
  file: path={{ alfresco_user_home }}/amps state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted|changed

- name: Create alfresco amp_share directory
  file: path={{ alfresco_user_home }}/amps_share state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted|changed

- name: Create alfresco log directory
  file: path={{ alfresco_log_home }} state=directory owner={{ alfresco_user }} group={{ alfresco_group }}
  when: alfresco_extracted|changed

- name: Install libreoffice startup script
  copy: src=start_oo.sh dest={{ alfresco_user_home }}/bin/start_oo.sh owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755
  when: alfresco_extracted|changed

- name: Install alfresco startup script
  template: src=alfresco.sh dest={{ alfresco_user_home }}/bin/alfresco.sh owner={{ alfresco_user }} group={{ alfresco_group }} mode=0755
  when: alfresco_extracted|changed

- name: Install alfresco init script
  template: src=alfresco dest=/etc/init.d/alfresco owner=root group=root mode=0755
  when: alfresco_extracted|changed

- name: Install alfresco global configuration
  template: src=alfresco-global.properties dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco-global.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed

- name: Install alfresco logging configuration
  template: src=custom-log4j.properties dest={{ alfresco_user_home }}/tomcat/shared/classes/alfresco/extension/custom-log4j.properties owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed

- name: Set alfresco file owner
  shell: chown -R {{ alfresco_user }}:{{ alfresco_group }} {{ alfresco_user_home }} && chown -R {{ alfresco_user }}:{{ alfresco_group }} /opt/apache-tomcat-{{ tomcat_version }}
  when: alfresco_extracted|changed

- name: Start alfresco server
  service: name=alfresco state=started
  when: alfresco_extracted|changed

- name: Wait for alfresco war deploy
  wait_for: path=/opt/alfresco/tomcat/webapps/alfresco/WEB-INF/web.xml
  when: alfresco_extracted|changed

- name: Relax security constraint for solr http comunication
  copy: src=web.xml dest={{ alfresco_user_home }}/tomcat/webapps/alfresco/WEB-INF/web.xml owner={{ alfresco_user }} group={{ alfresco_group }} mode=0644
  when: alfresco_extracted|changed
